theme: default
cleandestinationdir: true
disablekinds: ["RSS", "sitemap", "taxonomyTerm"]
publishdir: _site
staticDir:
  - static
# baseURL: https://syncthing.net/

markup:
  goldmark:
    renderer:
      unsafe: true
      
